server:
  http_listen_port: 3200

distributor:
  receivers: # this configuration will listen on all ports and protocols that tempo is capable of.
    otlp:
      protocols:
        http:
          endpoint: "tempo:4318"

ingester:
  trace_idle_period: 10s # the length of time after a trace has not received spans to consider it complete and flush it
  max_block_bytes: 1_000_000 # cut the head block when it hits this size or ...
  max_block_duration: 5m #   this much time passes

compactor:
  compaction:
    compaction_window: 1h # blocks in this time window will be compacted together
    max_block_bytes: 100_000_000 # maximum size of compacted blocks
    block_retention: 1h
    compacted_block_retention: 10m

metrics_generator:
  processor:
    service_graphs:
      histogram_buckets: [0.1, 0.2, 0.4, 0.8, 1.6, 3.2, 6.4, 12.8]
      dimensions:
        - job
        - service.name
        - service.namespace
        - service.instance.id
        - host
        - environment
        - net.k8s.name
        - net.peer.name
        - net.host.name
        - http.method
        - http.status_code
        - db.name
        - http.url
        - http.host
        - http.route
        - http.method
        - code.function
        - code.namespace
        - db.operation
        - db.sql.table
        - otel.library.version
    span_metrics:
      histogram_buckets:
        [
          0.002,
          0.004,
          0.008,
          0.016,
          0.032,
          0.064,
          0.128,
          0.256,
          0.512,
          1.02,
          2.05,
          4.10,
        ]
      dimensions:
        - job
        - service.name
        - service.namespace
        - service.instance.id
        - host
        - environment
        - net.k8s.name
        - net.peer.name
        - net.host.name
        - http.method
        - http.status_code
        - db.name
        - http.url
        - http.host
        - http.route
        - http.method
        - code.function
        - code.namespace
        - db.operation
        - db.sql.table
        - otel.library.version
      enable_target_info: false
  storage:
    path: /tmp/tempo/generator
    remote_write:
      - url: "http://mimir:9009/api/v1/push"
        send_exemplars: true

storage:
  trace:
    backend: local # backend configuration to use
    block:
      bloom_filter_false_positive: .05 # bloom filter false positive rate.  lower values create larger filters but fewer false positives
      v2_index_downsample_bytes: 1000 # number of bytes per index record
      v2_encoding: zstd # block encoding/compression.  options: none, gzip, lz4-64k, lz4-256k, lz4-1M, lz4, snappy, zstd, s2
    wal:
      path: /tmp/tempo/wal # where to store the the wal locally
      v2_encoding: snappy # wal encoding/compression.  options: none, gzip, lz4-64k, lz4-256k, lz4-1M, lz4, snappy, zstd, s2
    local:
      path: /tmp/tempo/blocks
    pool:
      max_workers: 100 # worker pool determines the number of parallel requests to the object store backend
      queue_depth: 10000

overrides:
  defaults:
    metrics_generator:
      processors:
        - service-graphs
        - span-metrics
